import os

MONGODB_PORT = os.getenv('MONGODB_PORT')
MONGODB_NAME = os.getenv('MONGODB_NAME')
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
GOOGLE_AI_API_KEY = os.getenv('GOOGLE_AI_API_KEY')
ALLOWED_TELEGRAM_USERNAMES = 5979279455
CHAT_HISTORY_LIMIT = 10
DEVELOPER_CHAT_ID = 5979279455
