version: "3"

services:
  gemini-telegram-bot:
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:?error}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:?error}
      - ALLOWED_TELEGRAM_USERNAMES=${ALLOWED_TELEGRAM_USERNAMES}
      - DEFAULT_CHAT_HISTORY_LIMIT=${DEFAULT_CHAT_HISTORY_LIMIT:-10}
      - DEFAULT_CHAT_TIMEOUT=${DEFAULT_CHAT_TIMEOUT:-7200}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    restart: always
    build:
      context: "."
